# coding: utf-8

"""
    Intercom API

    The intercom API reference.  # noqa: E501

    The version of the OpenAPI document: 2.9
    Generated by: https://openapi-generator.tech
"""

import unittest

import intercom_python_api
from intercom_python_api.model.detach_contact_from_conversation_request import DetachContactFromConversationRequest
from intercom_python_api import configuration


class TestDetachContactFromConversationRequest(unittest.TestCase):
    """DetachContactFromConversationRequest unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
