# coding: utf-8

"""
    Intercom API

    The intercom API reference.  # noqa: E501

    The version of the OpenAPI document: 2.9
    Generated by: https://openapi-generator.tech
"""

import unittest

import intercom_python_api
from intercom_python_api.model.create_message_request import CreateMessageRequest
from intercom_python_api import configuration


class TestCreateMessageRequest(unittest.TestCase):
    """CreateMessageRequest unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
