# coding: utf-8

"""
    Intercom API

    The intercom API reference.  # noqa: E501

    The version of the OpenAPI document: 2.8
    Generated by: https://openapi-generator.tech
"""

import unittest

import intercom_python_api
from intercom_python_api.model.article_translated_content import ArticleTranslatedContent
from intercom_python_api import configuration


class TestArticleTranslatedContent(unittest.TestCase):
    """ArticleTranslatedContent unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
