# coding: utf-8

"""
    Intercom API

    The intercom API reference.  # noqa: E501

    The version of the OpenAPI document: 2.8
    Generated by: https://openapi-generator.tech
"""

import unittest

import intercom_python_api
from intercom_python_api.model.create_or_update_tag_request import CreateOrUpdateTagRequest
from intercom_python_api import configuration


class TestCreateOrUpdateTagRequest(unittest.TestCase):
    """CreateOrUpdateTagRequest unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
