# coding: utf-8

"""
    Intercom API

    The intercom API reference.  # noqa: E501

    The version of the OpenAPI document: 2.8
    Generated by: https://openapi-generator.tech
"""

import unittest

import intercom_python_api
from intercom_python_api.model.tag_multiple_users_request import TagMultipleUsersRequest
from intercom_python_api import configuration


class TestTagMultipleUsersRequest(unittest.TestCase):
    """TagMultipleUsersRequest unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
