# coding: utf-8

"""
    Intercom API

    The intercom API reference.  # noqa: E501

    The version of the OpenAPI document: Unstable
    Generated by: https://openapi-generator.tech
"""

import unittest

import intercom_python_api
from intercom_python_api.model.update_contact_request import UpdateContactRequest
from intercom_python_api import configuration


class TestUpdateContactRequest(unittest.TestCase):
    """UpdateContactRequest unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
