# coding: utf-8

"""
    Intercom API

    The intercom API reference.  # noqa: E501

    The version of the OpenAPI document: Unstable
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from intercom_python_api import schemas  # noqa: F401


class TicketPart(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    A Ticket Part represents a message in the ticket.
    """


    class MetaOapg:
        
        class properties:
            type = schemas.StrSchema
            id = schemas.StrSchema
            part_type = schemas.StrSchema
            
            
            class body(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                def __new__(
                    cls,
                    *_args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'body':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                    )
            
            
            class previous_ticket_state(
                schemas.EnumBase,
                schemas.StrSchema
            ):
            
            
                class MetaOapg:
                    enum_value_to_name = {
                        "submitted": "SUBMITTED",
                        "in_progress": "IN_PROGRESS",
                        "waiting_on_customer": "WAITING_ON_CUSTOMER",
                        "resolved": "RESOLVED",
                    }
                
                @schemas.classproperty
                def SUBMITTED(cls):
                    return cls("submitted")
                
                @schemas.classproperty
                def IN_PROGRESS(cls):
                    return cls("in_progress")
                
                @schemas.classproperty
                def WAITING_ON_CUSTOMER(cls):
                    return cls("waiting_on_customer")
                
                @schemas.classproperty
                def RESOLVED(cls):
                    return cls("resolved")
            
            
            class ticket_state(
                schemas.EnumBase,
                schemas.StrSchema
            ):
            
            
                class MetaOapg:
                    enum_value_to_name = {
                        "submitted": "SUBMITTED",
                        "in_progress": "IN_PROGRESS",
                        "waiting_on_customer": "WAITING_ON_CUSTOMER",
                        "resolved": "RESOLVED",
                    }
                
                @schemas.classproperty
                def SUBMITTED(cls):
                    return cls("submitted")
                
                @schemas.classproperty
                def IN_PROGRESS(cls):
                    return cls("in_progress")
                
                @schemas.classproperty
                def WAITING_ON_CUSTOMER(cls):
                    return cls("waiting_on_customer")
                
                @schemas.classproperty
                def RESOLVED(cls):
                    return cls("resolved")
            created_at = schemas.IntSchema
            updated_at = schemas.IntSchema
        
            @staticmethod
            def assigned_to() -> typing.Type['Reference']:
                return Reference
        
            @staticmethod
            def author() -> typing.Type['TicketPartAuthor']:
                return TicketPartAuthor
            
            
            class attachments(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def items() -> typing.Type['PartAttachment']:
                        return PartAttachment
            
                def __new__(
                    cls,
                    _arg: typing.Union[typing.Tuple['PartAttachment'], typing.List['PartAttachment']],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'attachments':
                    return super().__new__(
                        cls,
                        _arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> 'PartAttachment':
                    return super().__getitem__(i)
            
            
            class external_id(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                def __new__(
                    cls,
                    *_args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'external_id':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                    )
            redacted = schemas.BoolSchema
            __annotations__ = {
                "type": type,
                "id": id,
                "part_type": part_type,
                "body": body,
                "previous_ticket_state": previous_ticket_state,
                "ticket_state": ticket_state,
                "created_at": created_at,
                "updated_at": updated_at,
                "assigned_to": assigned_to,
                "author": author,
                "attachments": attachments,
                "external_id": external_id,
                "redacted": redacted,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["type"]) -> MetaOapg.properties.type: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["id"]) -> MetaOapg.properties.id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["part_type"]) -> MetaOapg.properties.part_type: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["body"]) -> MetaOapg.properties.body: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["previous_ticket_state"]) -> MetaOapg.properties.previous_ticket_state: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["ticket_state"]) -> MetaOapg.properties.ticket_state: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["created_at"]) -> MetaOapg.properties.created_at: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["updated_at"]) -> MetaOapg.properties.updated_at: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["assigned_to"]) -> 'Reference': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["author"]) -> 'TicketPartAuthor': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["attachments"]) -> MetaOapg.properties.attachments: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["external_id"]) -> MetaOapg.properties.external_id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["redacted"]) -> MetaOapg.properties.redacted: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["type", "id", "part_type", "body", "previous_ticket_state", "ticket_state", "created_at", "updated_at", "assigned_to", "author", "attachments", "external_id", "redacted", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["type"]) -> typing.Union[MetaOapg.properties.type, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["id"]) -> typing.Union[MetaOapg.properties.id, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["part_type"]) -> typing.Union[MetaOapg.properties.part_type, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["body"]) -> typing.Union[MetaOapg.properties.body, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["previous_ticket_state"]) -> typing.Union[MetaOapg.properties.previous_ticket_state, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["ticket_state"]) -> typing.Union[MetaOapg.properties.ticket_state, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["created_at"]) -> typing.Union[MetaOapg.properties.created_at, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["updated_at"]) -> typing.Union[MetaOapg.properties.updated_at, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["assigned_to"]) -> typing.Union['Reference', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["author"]) -> typing.Union['TicketPartAuthor', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["attachments"]) -> typing.Union[MetaOapg.properties.attachments, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["external_id"]) -> typing.Union[MetaOapg.properties.external_id, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["redacted"]) -> typing.Union[MetaOapg.properties.redacted, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["type", "id", "part_type", "body", "previous_ticket_state", "ticket_state", "created_at", "updated_at", "assigned_to", "author", "attachments", "external_id", "redacted", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *_args: typing.Union[dict, frozendict.frozendict, ],
        type: typing.Union[MetaOapg.properties.type, str, schemas.Unset] = schemas.unset,
        id: typing.Union[MetaOapg.properties.id, str, schemas.Unset] = schemas.unset,
        part_type: typing.Union[MetaOapg.properties.part_type, str, schemas.Unset] = schemas.unset,
        body: typing.Union[MetaOapg.properties.body, None, str, schemas.Unset] = schemas.unset,
        previous_ticket_state: typing.Union[MetaOapg.properties.previous_ticket_state, str, schemas.Unset] = schemas.unset,
        ticket_state: typing.Union[MetaOapg.properties.ticket_state, str, schemas.Unset] = schemas.unset,
        created_at: typing.Union[MetaOapg.properties.created_at, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        updated_at: typing.Union[MetaOapg.properties.updated_at, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        assigned_to: typing.Union['Reference', schemas.Unset] = schemas.unset,
        author: typing.Union['TicketPartAuthor', schemas.Unset] = schemas.unset,
        attachments: typing.Union[MetaOapg.properties.attachments, list, tuple, schemas.Unset] = schemas.unset,
        external_id: typing.Union[MetaOapg.properties.external_id, None, str, schemas.Unset] = schemas.unset,
        redacted: typing.Union[MetaOapg.properties.redacted, bool, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'TicketPart':
        return super().__new__(
            cls,
            *_args,
            type=type,
            id=id,
            part_type=part_type,
            body=body,
            previous_ticket_state=previous_ticket_state,
            ticket_state=ticket_state,
            created_at=created_at,
            updated_at=updated_at,
            assigned_to=assigned_to,
            author=author,
            attachments=attachments,
            external_id=external_id,
            redacted=redacted,
            _configuration=_configuration,
            **kwargs,
        )

from intercom_python_api.model.part_attachment import PartAttachment
from intercom_python_api.model.reference import Reference
from intercom_python_api.model.ticket_part_author import TicketPartAuthor
