# coding: utf-8

"""
    Intercom API

    The intercom API reference.  # noqa: E501

    The version of the OpenAPI document: 2.7
    Generated by: https://openapi-generator.tech
"""

from intercom_python_api.paths.articles.post import CreateArticle
from intercom_python_api.paths.articles_id.delete import DeleteArticle
from intercom_python_api.paths.articles.get import ListArticles
from intercom_python_api.paths.articles_id.get import RetrieveArticle
from intercom_python_api.paths.articles_id.put import UpdateArticle


class ArticlesApi(
    CreateArticle,
    DeleteArticle,
    ListArticles,
    RetrieveArticle,
    UpdateArticle,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
