# coding: utf-8

"""
    Intercom API

    The intercom API reference.  # noqa: E501

    The version of the OpenAPI document: Unstable
    Generated by: https://openapi-generator.tech
"""

from intercom_python_api.paths.help_center_collections.post import CreateCollection
from intercom_python_api.paths.help_center_collections_id.delete import DeleteCollection
from intercom_python_api.paths.help_center_collections.get import ListAllCollections
from intercom_python_api.paths.help_center_collections_id.get import RetrieveCollection
from intercom_python_api.paths.help_center_collections_id.put import UpdateCollection


class HelpCenterApi(
    CreateCollection,
    DeleteCollection,
    ListAllCollections,
    RetrieveCollection,
    UpdateCollection,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
