# coding: utf-8

"""
    Intercom API

    The intercom API reference.  # noqa: E501

    The version of the OpenAPI document: Unstable
    Generated by: https://openapi-generator.tech
"""

from intercom_python_api.paths.contacts_id_notes.post import CreateNote
from intercom_python_api.paths.contacts_id_notes.get import ListNotes
from intercom_python_api.paths.notes_id.get import RetrieveNote


class NotesApi(
    CreateNote,
    ListNotes,
    RetrieveNote,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
