# coding: utf-8

"""
    Intercom API

    The intercom API reference.  # noqa: E501

    The version of the OpenAPI document: 2.7
    Generated by: https://openapi-generator.tech
"""

from intercom_python_api.paths.contacts_contact_id_subscriptions.post import AttachSubscriptionTypeToContact
from intercom_python_api.paths.contacts_contact_id_subscriptions_id.delete import DetachSubscriptionTypeToContact
from intercom_python_api.paths.subscription_types.get import ListSubscriptionTypes
from intercom_python_api.paths.contacts_contact_id_subscriptions.get import ListSubscriptionsForAContact


class SubscriptionTypesApi(
    AttachSubscriptionTypeToContact,
    DetachSubscriptionTypeToContact,
    ListSubscriptionTypes,
    ListSubscriptionsForAContact,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
